language: node_js

node_js:
   - "8.9"

install:
  - npm install -g bower
  - bower install
  - npm install -g firebase-tools

after_success:
  - firebase deploy

sudo: false

branches:
  only:
    - master
