language: node_js

node_js:
   - "8.9"

install:
  - npm install -g bower firebase-tools
  - bower install
  - cd functions
  - npm install

after_success:
  - firebase deploy

sudo: false

branches:
  only:
    - master
