language: node_js

node_js:
   - "5.0"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}

sudo: false

branches:
  only:
    - master
